meta_name: "EcoCcoach"
meta_title: "EcoCoach - Become an eco-citizen"
meta_description: "Get a coach and stay motivated to act on climate change. A gamified app with custom challenges and useful tips to help you riching your eco-goals. "
meta_image: "meta-image.jpg" # should exist in `app/assets/images/`
